# FetchFFTW.cmake
#
# Build FFTW (the classic reference FFT) from source via FetchContent and expose
# it as the imported target FFTW::FFTW for the benchmark-only FFTW backend.
#
# BENCHMARK ONLY. FFTW is GPL-2.0-or-later / commercial (dual). Like KFR it must
# never be linked into or packaged with a production artifact; the CMakeLists
# licensing guard forbids it when FFT_PACKAGING is ON.
#
# Single precision (ENABLE_FLOAT -> the fftw3f target), which is what the c2c f32
# benchmark drives. Built static and single-threaded, matching the rest of the
# benchmark setup. FFTW compiles every enabled SIMD codelet set and selects the
# best at runtime, so we enable the vector ISAs this host supports (SSE2/AVX/AVX2
# on x86, NEON on Arm — NEON is single-precision only, which is exactly our build).

include_guard(GLOBAL)

if(TARGET FFTW::FFTW)
    return()
endif()

# FFTW is C; make sure C is enabled in case the parent project is CXX-only.
enable_language(C)

include(FetchContent)

set(BUILD_SHARED_LIBS OFF CACHE BOOL "" FORCE)     # static, not shared
set(BUILD_TESTS OFF CACHE BOOL "" FORCE)           # no test/benchmark subtree
set(ENABLE_FLOAT ON CACHE BOOL "" FORCE)           # build the single-precision fftw3f
set(ENABLE_LONG_DOUBLE OFF CACHE BOOL "" FORCE)
set(ENABLE_QUAD_PRECISION OFF CACHE BOOL "" FORCE)
set(ENABLE_THREADS OFF CACHE BOOL "" FORCE)        # single-threaded
set(DISABLE_FORTRAN ON CACHE BOOL "" FORCE)

if(CMAKE_SYSTEM_PROCESSOR MATCHES "x86_64|AMD64|i[3-6]86|x86")
    set(ENABLE_SSE2 ON CACHE BOOL "" FORCE)
    set(ENABLE_AVX ON CACHE BOOL "" FORCE)
    set(ENABLE_AVX2 ON CACHE BOOL "" FORCE)
elseif(CMAKE_SYSTEM_PROCESSOR MATCHES "arm|aarch64")
    set(ENABLE_NEON ON CACHE BOOL "" FORCE)
endif()

# Fetch the official release TARBALL, not the git repo: FFTW's SIMD codelet .c
# files (dft/simd/sse2/*.c, avx, avx2, neon, ...) are pre-generated by FFTW's
# OCaml codelet generator and shipped only in the release tarball. The git repo
# ships those directories with headers but no generated .c, so a CMake build from
# git fails to link (undefined fftwf_solvtab_dft_sse2, ...). The tarball is
# self-contained and needs no code generation.
FetchContent_Declare(fftw
    URL https://www.fftw.org/fftw-3.3.10.tar.gz
    URL_HASH SHA256=56c932549852cddcfafdab3820b0200c7742675be92179e59e6215b340e26467)
FetchContent_MakeAvailable(fftw)

# FFTW's single-precision library target is fftw3f.
if(TARGET fftw3f)
    set(_fftw_target fftw3f)
else()
    message(FATAL_ERROR "FFTW: expected static target fftw3f not found after fetch")
endif()

add_library(FFTW::FFTW INTERFACE IMPORTED GLOBAL)
target_link_libraries(FFTW::FFTW INTERFACE ${_fftw_target})
# Public header fftw3.h lives under api/; FFTW does not export it for in-tree
# consumers, so add it explicitly.
target_include_directories(FFTW::FFTW INTERFACE "${fftw_SOURCE_DIR}/api")

message(STATUS "FFTW: built static single-precision (fftw3f), headers ${fftw_SOURCE_DIR}/api")
